version: '3'
services:
  # APP**
  invest:
    container_name: investback
    build: src
    ports:
      - "8082:8081"
    environment:
          POSTGRES_HOST: database
          POSTGRES_USER: "invest"
          POSTGRES_DB: "postgres"
          POSTGRES_PASSWORD: "invest"

  database:
    container_name: investdb
    image: library/postgres:12-alpine
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: "invest"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "invest"

