server:
  port: 8081
spring:
  main:
    banner-mode: log
  datasource:
    #url: jdbc:postgresql://172.30.0.1:5437/postgres
    url: jdbc:postgresql://localhost:5437/postgres
    username: invest
    password: invest
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  flyway:
    check-location: false

tcsbroker:
  url: https://api-invest.tinkoff.ru/openapi/

bot:
  name: AnalizePortfolioInvestmentBot
  token: